"""Your migration message here

Revision ID: 16ac7fadc1fe
Revises: 75abe3009382
Create Date: 2025-01-01 21:27:16.255525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16ac7fadc1fe'
down_revision = '75abe3009382'
branch_labels = None
depends_on = None


def upgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    #with op.batch_alter_table('entries_workers', schema=None) as batch_op:
        #batch_op.drop_index('ix_entries_workers_date_of_report')

    #op.drop_table('entries_workers')
    #op.drop_table('subcontractor_entries')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subcontractor_entries',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('subcontractor_id', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('task_id', sa.INTEGER(), nullable=True),
    sa.Column('work_order_id', sa.INTEGER(), nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('equipment_hours', sa.FLOAT(), server_default=sa.text("'0'"), nullable=True),
    sa.Column('material_cost', sa.FLOAT(), server_default=sa.text("'0'"), nullable=True),
    sa.Column('labor_hours', sa.FLOAT(), server_default=sa.text("'0'"), nullable=True),
    sa.Column('total_cost', sa.FLOAT(), server_default=sa.text("'0'"), nullable=True),
    sa.Column('progress_percentage', sa.FLOAT(), server_default=sa.text("'0'"), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['subcontractor_id'], ['subcontractors.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['project_tasks.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entries_workers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date_of_report', sa.DATE(), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('worker_id', sa.INTEGER(), nullable=False),
    sa.Column('hours_worked', sa.FLOAT(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('activity_id', sa.INTEGER(), nullable=True),
    sa.Column('cwp', sa.VARCHAR(length=50), nullable=True),
    sa.Column('phase', sa.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity_codes.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entries_workers', schema=None) as batch_op:
        batch_op.create_index('ix_entries_workers_date_of_report', ['date_of_report'], unique=False)

    # ### end Alembic commands ###
