"""Add activity_code_id to work_order_entries (if you added it)

Revision ID: 1f77c651f661
Revises: c0b5314da89b
Create Date: 2025-01-02 00:32:46.258711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f77c651f661'
down_revision = 'c0b5314da89b'
branch_labels = None
depends_on = None


def upgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('entries_material')
    #with op.batch_alter_table('entries_workers', schema=None) as batch_op:
     #   batch_op.drop_index('ix_entries_workers_date_of_report')

    #op.drop_table('entries_workers')
    #with op.batch_alter_table('entries_equipment', schema=None) as batch_op:
     #   batch_op.drop_index('ix_entries_equipment_date_of_report')

    #op.drop_table('entries_equipment')
    #op.drop_table('subcontractor_entries')
    #flask dowgrade  ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subcontractor_entries',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('subcontractor_id', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('task_id', sa.INTEGER(), nullable=True),
    sa.Column('work_order_id', sa.INTEGER(), nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('equipment_hours', sa.FLOAT(), server_default=sa.text("'0'"), nullable=True),
    sa.Column('material_cost', sa.FLOAT(), server_default=sa.text("'0'"), nullable=True),
    sa.Column('labor_hours', sa.FLOAT(), server_default=sa.text("'0'"), nullable=True),
    sa.Column('total_cost', sa.FLOAT(), server_default=sa.text("'0'"), nullable=True),
    sa.Column('progress_percentage', sa.FLOAT(), server_default=sa.text("'0'"), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['subcontractor_id'], ['subcontractors.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['project_tasks.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entries_equipment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date_of_report', sa.DATE(), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('equipment_id', sa.INTEGER(), nullable=False),
    sa.Column('hours_used', sa.FLOAT(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('activity_id', sa.INTEGER(), nullable=True),
    sa.Column('cwp', sa.VARCHAR(length=50), nullable=True),
    sa.Column('phase', sa.VARCHAR(length=50), nullable=True),
    sa.Column('usage_description', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity_codes.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entries_equipment', schema=None) as batch_op:
        batch_op.create_index('ix_entries_equipment_date_of_report', ['date_of_report'], unique=False)

    op.create_table('entries_workers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date_of_report', sa.DATE(), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('worker_id', sa.INTEGER(), nullable=False),
    sa.Column('hours_worked', sa.FLOAT(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('activity_id', sa.INTEGER(), nullable=True),
    sa.Column('cwp', sa.VARCHAR(length=50), nullable=True),
    sa.Column('phase', sa.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity_codes.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entries_workers', schema=None) as batch_op:
        batch_op.create_index('ix_entries_workers_date_of_report', ['date_of_report'], unique=False)

    op.create_table('entries_material',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('material_id', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('purchase_order_id', sa.INTEGER(), nullable=True),
    sa.Column('activity_code_id', sa.INTEGER(), nullable=True),
    sa.Column('task_id', sa.INTEGER(), nullable=True),
    sa.Column('work_order_id', sa.INTEGER(), nullable=True),
    sa.Column('material_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('unit', sa.VARCHAR(length=50), nullable=True),
    sa.Column('unit_price', sa.FLOAT(), nullable=True),
    sa.Column('quantity_used', sa.FLOAT(), nullable=True),
    sa.Column('supplier_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('cost', sa.FLOAT(), nullable=True),
    sa.Column('procurement_status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['activity_code_id'], ['activity_codes.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['project_tasks.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
