"""Add activity_code_id to SubcontractorEntry

Revision ID: 210d6b2a1c27
Revises: 721ee7d93f96
Create Date: 2025-01-05 13:02:42.340088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '210d6b2a1c27'
down_revision = '721ee7d93f96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.alter_column('procurement_group',
               existing_type=sa.BLOB(),
               type_=sa.Enum('direct', 'bulk', 'rental', name='procurement_group_enum'),
               existing_nullable=False)
        batch_op.alter_column('delivery_location',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('subcontractor_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity_code_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key("fk_subcontractor_entries_activity_code", 'activity_codes', ['activity_code_id'], ['id'])

    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('progress_percentage', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.drop_column('progress_percentage')

    with op.batch_alter_table('subcontractor_entries', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('activity_code_id')

    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.alter_column('delivery_location',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('procurement_group',
               existing_type=sa.Enum('direct', 'bulk', 'rental', name='procurement_group_enum'),
               type_=sa.BLOB(),
               existing_nullable=False)

    # ### end Alembic commands ###
