"""your message here (e.g. add status column to daily_notes)

Revision ID: 4c8aeee2f6e2
Revises: 58d047aa7493
Create Date: 2025-05-20 14:55:19.483342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c8aeee2f6e2'
down_revision = '58d047aa7493'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entries_daily_notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_of_report', sa.Date(), nullable=False, server_default=sa.text("CURRENT_DATE")))
        batch_op.add_column(sa.Column('status', sa.Enum('pending', 'committed', 'rejected', name='entry_status'), nullable=True))
        batch_op.create_index(batch_op.f('ix_entries_daily_notes_date_of_report'), ['date_of_report'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entries_daily_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entries_daily_notes_date_of_report'))
        batch_op.drop_column('status')
        batch_op.drop_column('date_of_report')

    # ### end Alembic commands ###
