"""Initial migration

Revision ID: 51b43ac9c130
Revises: 
Create Date: 2024-12-30 21:39:19.590778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51b43ac9c130'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('cwp', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('std_man_hours_per_unit', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['project_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_codes_code'), ['code'], unique=True)

    op.create_table('materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('cost_per_unit', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material_id')
    )
    op.create_table('payment_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_code', sa.String(length=50), nullable=False),
    sa.Column('default_activity_code_id', sa.Integer(), nullable=True),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('rate_per_unit', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['default_activity_code_id'], ['activity_codes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_items_item_name'), ['item_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_items_payment_code'), ['payment_code'], unique=True)

    op.create_table('project_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('not_started', 'in_progress', 'completed', name='task_status'), nullable=True),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('man_hour_budget', sa.Float(), nullable=True),
    sa.Column('man_hours', sa.Float(), nullable=True),
    sa.Column('payment_item_id', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('qte', sa.Float(), nullable=True),
    sa.Column('PV', sa.Float(), nullable=True),
    sa.Column('EV', sa.Float(), nullable=True),
    sa.Column('AC', sa.Float(), nullable=True),
    sa.Column('CV', sa.Float(), nullable=True),
    sa.Column('SV', sa.Float(), nullable=True),
    sa.Column('VAC', sa.Float(), nullable=True),
    sa.Column('CPI', sa.Float(), nullable=True),
    sa.Column('SPI', sa.Float(), nullable=True),
    sa.Column('EAC', sa.Float(), nullable=True),
    sa.Column('ETC', sa.Float(), nullable=True),
    sa.Column('TCPI', sa.Float(), nullable=True),
    sa.Column('CWP', sa.String(length=100), nullable=True),
    sa.Column('specialty', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['payment_item_id'], ['payment_items.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('project_number', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('planned', 'in_progress', 'completed', 'on_hold', 'canceled', name='project_status'), nullable=True),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('project_manager', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('original_budget', sa.Float(), nullable=True),
    sa.Column('revised_budget', sa.Float(), nullable=True),
    sa.Column('contingency_fund', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.Enum('low', 'medium', 'high', name='project_risk_level'), nullable=True),
    sa.Column('risk_notes', sa.Text(), nullable=True),
    sa.Column('map_url', sa.String(length=2083), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('picture_url', sa.String(length=2083), nullable=True),
    sa.Column('video_capture_url', sa.String(length=2083), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('plan_repository_url', sa.String(length=2083), nullable=True),
    sa.Column('sustainability_rating', sa.Enum('basic', 'silver', 'gold', 'platinum', name='sustainability_rating'), nullable=True),
    sa.Column('sustainability_goals', sa.Text(), nullable=True),
    sa.Column('collaboration_url', sa.String(length=2083), nullable=True),
    sa.Column('integration_status', sa.Boolean(), nullable=True),
    sa.Column('audit_due_date', sa.Date(), nullable=True),
    sa.Column('compliance_status', sa.Enum('pending', 'approved', 'non_compliant', name='compliance_status'), nullable=True),
    sa.Column('local_hires', sa.Integer(), nullable=True),
    sa.Column('community_engagement_notes', sa.Text(), nullable=True),
    sa.Column('previous_project_id', sa.Integer(), nullable=True),
    sa.Column('benchmark_cost_per_unit', sa.Float(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('critical_path_duration', sa.Integer(), nullable=True),
    sa.Column('key_milestones', sa.JSON(), nullable=True),
    sa.Column('safety_incidents', sa.Integer(), nullable=True),
    sa.Column('incident_notes', sa.Text(), nullable=True),
    sa.Column('bim_file_url', sa.String(length=2083), nullable=True),
    sa.Column('bim_model_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['previous_project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_end_date'), ['end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_project_number'), ['project_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_projects_start_date'), ['start_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_status'), ['status'], unique=False)

    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=True),
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('vendor', sa.String(length=255), nullable=False),
    sa.Column('vendor_address', sa.String(length=255), nullable=True),
    sa.Column('vendor_phone', sa.String(length=50), nullable=True),
    sa.Column('vendor_general_email', sa.String(length=255), nullable=True),
    sa.Column('vendor_accounting_email', sa.String(length=255), nullable=True),
    sa.Column('vendor_contact_name', sa.String(length=255), nullable=True),
    sa.Column('vendor_contact_phone', sa.String(length=50), nullable=True),
    sa.Column('vendor_contact_email', sa.String(length=255), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.String(length=100), nullable=True),
    sa.Column('equipment_id', sa.String(length=100), nullable=True),
    sa.Column('worker_id', sa.Integer(), nullable=True),
    sa.Column('subcontractor_id', sa.Integer(), nullable=True),
    sa.Column('service_name', sa.String(length=255), nullable=True),
    sa.Column('activity_code_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('quantity_purchased', sa.Float(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('procurement_group', sa.Enum('direct', 'bulk', 'rental', name='procurement_group_enum'), nullable=False),
    sa.Column('procurement_type', sa.Enum('material', 'equipment', 'worker', 'subcontractor', 'service', name='procurement_type_enum'), nullable=False),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('delivery_location', sa.String(length=255), nullable=True),
    sa.Column('link_to_supplier_quote', sa.String(length=2083), nullable=True),
    sa.Column('quantity_consumed', sa.Float(), nullable=True),
    sa.Column('delivery_compliance', sa.Enum('on_time', 'late', 'partial', 'not_delivered', name='delivery_compliance_enum'), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.Column('is_change_order', sa.Boolean(), nullable=False),
    sa.Column('linked_po_id', sa.Integer(), nullable=True),
    sa.Column('on_site_status', sa.Enum('pending', 'received', 'inspected', 'rejected', name='on_site_status_enum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['activity_code_id'], ['activity_codes.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.equipment_id'], ),
    sa.ForeignKeyConstraint(['linked_po_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.material_id'], ),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['subcontractor_id'], ['subcontractors.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['project_tasks.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_number')
    )
    op.create_table('daily_report_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('workers_tab', sa.Enum('pending', 'in_progress', 'completed', name='tab_status'), nullable=True),
    sa.Column('materials_tab', sa.Enum('pending', 'in_progress', 'completed', name='tab_status'), nullable=True),
    sa.Column('equipment_tab', sa.Enum('pending', 'in_progress', 'completed', name='tab_status'), nullable=True),
    sa.Column('notes_tab', sa.Enum('pending', 'in_progress', 'completed', name='tab_status'), nullable=True),
    sa.Column('pictures_tab', sa.Enum('pending', 'in_progress', 'completed', name='tab_status'), nullable=True),
    sa.Column('subcontractors_tab', sa.Enum('pending', 'in_progress', 'completed', name='tab_status'), nullable=True),
    sa.Column('workorders_tab', sa.Enum('pending', 'in_progress', 'completed', name='tab_status'), nullable=True),
    sa.Column('report_status', sa.Enum('pending', 'in_progress', 'completed', name='report_status_enum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('assigned_to', sa.String(length=100), nullable=True),
    sa.Column('assigned_project_id', sa.Integer(), nullable=True),
    sa.Column('maintenance_status', sa.Enum('operational', 'under_maintenance', 'out_of_service', name='equipment_status_enum'), nullable=False),
    sa.Column('hourly_rate', sa.Float(), nullable=True),
    sa.Column('last_maintenance_date', sa.DateTime(), nullable=True),
    sa.Column('next_maintenance_date', sa.DateTime(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('device_id', sa.String(length=100), nullable=True),
    sa.Column('telemetry_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id'),
    sa.UniqueConstraint('equipment_id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_table('purchase_order_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.String(length=2083), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subcontractors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('task', sa.String(length=255), nullable=False),
    sa.Column('contract_type', sa.Enum('fixed_amount', 'cost_plus_expenses', 'time_and_materials', name='contract_type_enum'), nullable=False),
    sa.Column('total_contract_value', sa.Float(), nullable=True),
    sa.Column('progress_percentage', sa.Float(), nullable=True),
    sa.Column('payment_status', sa.Enum('pending', 'partial', 'paid', 'overdue', name='subcontractor_payment_status'), nullable=True),
    sa.Column('payment_terms', sa.String(length=255), nullable=True),
    sa.Column('last_payment_date', sa.Date(), nullable=True),
    sa.Column('cost_plus_total', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('genre', sa.Enum('male', 'female', 'other', name='worker_genre'), nullable=True),
    sa.Column('worker_id', sa.String(length=50), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('code_postal', sa.String(length=10), nullable=True),
    sa.Column('num_cell', sa.String(length=15), nullable=True),
    sa.Column('courriel', sa.String(length=255), nullable=True),
    sa.Column('certifications', sa.JSON(), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('login_attempts', sa.Integer(), nullable=True),
    sa.Column('metier', sa.String(length=100), nullable=True),
    sa.Column('convention', sa.String(length=100), nullable=True),
    sa.Column('taux_horaire', sa.Float(), nullable=True),
    sa.Column('taux_over', sa.Float(), nullable=True),
    sa.Column('Gite_couvert', sa.Float(), nullable=True),
    sa.Column('transp_1', sa.Float(), nullable=True),
    sa.Column('transp_2', sa.Float(), nullable=True),
    sa.Column('equip_asso', sa.String(length=255), nullable=True),
    sa.Column('departement', sa.String(length=100), nullable=True),
    sa.Column('role', sa.Enum('admin', 'manager', 'superintendant', 'foreman', 'worker', name='user_roles'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='fk_worker_project'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('courriel'),
    sa.UniqueConstraint('worker_id')
    )
    op.create_table('daily_report_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('activity_code_id', sa.Integer(), nullable=True),
    sa.Column('payment_item_id', sa.Integer(), nullable=True),
    sa.Column('worker_id', sa.Integer(), nullable=True),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('po_id', sa.Integer(), nullable=True),
    sa.Column('quantity_used', sa.Float(), nullable=True),
    sa.Column('equipment_id', sa.Integer(), nullable=True),
    sa.Column('subcontractor_id', sa.Integer(), nullable=True),
    sa.Column('daily_log_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('hours', sa.Float(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('CWP', sa.String(length=100), nullable=True),
    sa.Column('phase', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['activity_code_id'], ['activity_codes.id'], ),
    sa.ForeignKeyConstraint(['daily_log_id'], ['daily_report_data.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['payment_item_id'], ['payment_items.id'], ),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['subcontractor_id'], ['subcontractors.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['project_tasks.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment_assignments',
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('worker_id', 'equipment_id')
    )
    op.create_table('work_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('sequential_number', sa.String(length=10), nullable=False),
    sa.Column('work_order_number', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('subcontractor_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('change_order', 'additional_scope', 'emergency', name='work_order_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('open', 'in_progress', 'completed', 'canceled', 'deferred', name='work_order_status_enum'), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('cumulative_actual_cost', sa.Float(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('expected_completion_date', sa.Date(), nullable=True),
    sa.Column('requested_date', sa.Date(), nullable=True),
    sa.Column('approved_date', sa.Date(), nullable=True),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.Column('activity_code', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['subcontractor_id'], ['subcontractors.id'], ),
    sa.ForeignKeyConstraint(['work_order_number'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activity_code'),
    sa.UniqueConstraint('sequential_number')
    )
    op.create_table('daily_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('daily_log_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', name='note_priority_enum'), nullable=True),
    sa.Column('linked_activity_code', sa.Integer(), nullable=True),
    sa.Column('attachment_url', sa.String(length=2083), nullable=True),
    sa.Column('editable_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['daily_log_id'], ['daily_report_data.id'], ),
    sa.ForeignKeyConstraint(['linked_activity_code'], ['activity_codes.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sustainability_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('daily_log_id', sa.Integer(), nullable=True),
    sa.Column('metric_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('energy', 'emissions', 'water', 'waste', 'materials', name='sustainability_category'), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('target_value', sa.Float(), nullable=True),
    sa.Column('deviation', sa.Float(), nullable=True),
    sa.Column('triggered_alert', sa.Boolean(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.Column('recorded_by', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['daily_log_id'], ['daily_report_data.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['project_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tab_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('daily_log_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('tab_name', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('incomplete', 'in_review', 'completed', 'approved', 'rejected', name='tab_status'), nullable=True),
    sa.Column('progress_percentage', sa.Float(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=True),
    sa.Column('status_history', sa.JSON(), nullable=True),
    sa.Column('tab_notes', sa.Text(), nullable=True),
    sa.Column('last_updated_by', sa.String(length=255), nullable=True),
    sa.Column('reviewed_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['daily_log_id'], ['daily_report_data.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weather_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('daily_log_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', name='weather_severity_enum'), nullable=True),
    sa.Column('work_impact', sa.Enum('none', 'partial_delay', 'full_stop', name='weather_impact_enum'), nullable=True),
    sa.Column('delay_reason', sa.Text(), nullable=True),
    sa.Column('hours_lost', sa.Float(), nullable=True),
    sa.Column('impacted_activity_codes', sa.JSON(), nullable=True),
    sa.Column('api_data', sa.JSON(), nullable=True),
    sa.Column('trend', sa.String(length=50), nullable=True),
    sa.Column('predicted_hours_lost', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['daily_log_id'], ['daily_report_data.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_pictures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('daily_log_id', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.String(length=2083), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('taken_at', sa.DateTime(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('activity_code', sa.String(length=50), nullable=True),
    sa.Column('work_order_id', sa.Integer(), nullable=True),
    sa.Column('daily_note_id', sa.Integer(), nullable=True),
    sa.Column('coordinates', sa.JSON(), nullable=True),
    sa.Column('position', sa.String(length=255), nullable=True),
    sa.Column('size', sa.Float(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('captured_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['activity_code'], ['activity_codes.id'], ),
    sa.ForeignKeyConstraint(['daily_log_id'], ['daily_report_data.id'], ),
    sa.ForeignKeyConstraint(['daily_note_id'], ['daily_notes.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('daily_log_id', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.String(length=2083), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('document_type', sa.Enum('h_s', 'environment', 'field_inspection', 'maintenance', 'general', name='document_type_enum'), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('daily_note_id', sa.Integer(), nullable=True),
    sa.Column('picture_repository_url', sa.String(length=2083), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('approval_date', sa.DateTime(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_modified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['daily_log_id'], ['daily_report_data.id'], ),
    sa.ForeignKeyConstraint(['daily_note_id'], ['daily_notes.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documents')
    op.drop_table('daily_pictures')
    op.drop_table('weather_logs')
    op.drop_table('tab_progress')
    op.drop_table('sustainability_metrics')
    op.drop_table('daily_notes')
    op.drop_table('work_orders')
    op.drop_table('equipment_assignments')
    op.drop_table('daily_report_data')
    op.drop_table('workers')
    op.drop_table('subcontractors')
    op.drop_table('purchase_order_attachments')
    op.drop_table('equipment')
    op.drop_table('daily_report_statuses')
    op.drop_table('purchase_orders')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_status'))
        batch_op.drop_index(batch_op.f('ix_projects_start_date'))
        batch_op.drop_index(batch_op.f('ix_projects_project_number'))
        batch_op.drop_index(batch_op.f('ix_projects_end_date'))
        batch_op.drop_index(batch_op.f('ix_projects_category'))

    op.drop_table('projects')
    op.drop_table('project_tasks')
    with op.batch_alter_table('payment_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_items_payment_code'))
        batch_op.drop_index(batch_op.f('ix_payment_items_item_name'))

    op.drop_table('payment_items')
    op.drop_table('materials')
    with op.batch_alter_table('activity_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_codes_code'))

    op.drop_table('activity_codes')
    # ### end Alembic commands ###
