"""activitycode project.id nullable=True

Revision ID: 5c9128ba1ba0
Revises: 210d6b2a1c27
Create Date: 2025-01-07 16:04:38.690823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c9128ba1ba0'
down_revision = '210d6b2a1c27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_codes', schema=None) as batch_op:
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.alter_column('purchase_order_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('payment_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('default_activity_code_id')

    with op.batch_alter_table('project_tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('payment_item_id')

    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('material_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('material_id', sa.VARCHAR(length=100), nullable=True))
        batch_op.create_foreign_key(None, 'materials', ['material_id'], ['material_id'], ondelete='SET NULL')

    with op.batch_alter_table('project_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_item_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'payment_items', ['payment_item_id'], ['id'])

    with op.batch_alter_table('payment_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_activity_code_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'activity_codes', ['default_activity_code_id'], ['id'])

    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('purchase_order_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('activity_codes', schema=None) as batch_op:
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
