"""empty message

Revision ID: 5e6b94a4fbe7
Revises: a1d14fad43e3
Create Date: 2025-01-07 18:23:37.650669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e6b94a4fbe7'
down_revision = 'a1d14fad43e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subcontractors', schema=None) as batch_op:
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('task',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('contract_type',
               existing_type=sa.VARCHAR(length=18),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subcontractors', schema=None) as batch_op:
        batch_op.alter_column('contract_type',
               existing_type=sa.VARCHAR(length=18),
               nullable=False)
        batch_op.alter_column('task',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
