"""Add activity_code_id column to purchase_orders

Revision ID: 721ee7d93f96
Revises: 848e5965bb98
Create Date: 2025-01-05 12:06:00.165044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '721ee7d93f96'
down_revision = '848e5965bb98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #with op.batch_alter_table('entries_equipment', schema=None) as batch_op:
    #    batch_op.add_column(sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', name='entry_status'), nullable=False))

    #with op.batch_alter_table('entries_material', schema=None) as batch_op:
    #    batch_op.add_column(sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', name='entry_status'), nullable=False))

    #with op.batch_alter_table('entries_workers', schema=None) as batch_op:
    #    batch_op.add_column(sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', name='entry_status'), nullable=False))

    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity_code_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key("fk_purchase_orders_activity_code", 'activity_codes', ['activity_code_id'], ['id'])

    with op.batch_alter_table('subcontractor_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', name='entry_status'), nullable=False))

    with op.batch_alter_table('work_order_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', name='entry_status'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_order_entries', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('subcontractor_entries', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('activity_code_id')

    with op.batch_alter_table('entries_workers', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('entries_material', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('entries_equipment', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
