"""empty message

Revision ID: 981df2019120
Revises: a52a8f75336c
Create Date: 2025-01-07 17:54:48.349841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '981df2019120'
down_revision = 'a52a8f75336c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.alter_column('maintenance_status',
               existing_type=sa.VARCHAR(length=17),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.alter_column('maintenance_status',
               existing_type=sa.VARCHAR(length=17),
               nullable=False)

    # ### end Alembic commands ###
