"""empty message

Revision ID: c15b5017dec3
Revises: d31164de7d53
Create Date: 2025-01-07 18:17:53.754237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c15b5017dec3'
down_revision = 'd31164de7d53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.alter_column('total_cost',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('procurement_group',
               existing_type=sa.VARCHAR(length=6),
               nullable=True)
        batch_op.alter_column('procurement_type',
               existing_type=sa.VARCHAR(length=13),
               nullable=True)
        batch_op.alter_column('is_change_order',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.alter_column('is_change_order',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('procurement_type',
               existing_type=sa.VARCHAR(length=13),
               nullable=False)
        batch_op.alter_column('procurement_group',
               existing_type=sa.VARCHAR(length=6),
               nullable=False)
        batch_op.alter_column('total_cost',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###
