"""empty message

Revision ID: d25a0182c9c7
Revises: 2912bc5d2a06
Create Date: 2025-01-01 19:06:13.868641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd25a0182c9c7'
down_revision = '2912bc5d2a06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_codes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_activity_codes_task_id', type_='foreignkey')
        batch_op.drop_column('task_id')
        op.create_table(
        'entries_workers',
        sa.Column('id', sa.Integer, primary_key=True, autoincrement=True),
        sa.Column('date_of_report', sa.Date(), nullable=False, index=True),
        sa.Column('project_id', sa.Integer, sa.ForeignKey('projects.id'), nullable=False),
        sa.Column('worker_id', sa.Integer, sa.ForeignKey('workers.id'), nullable=False),
        sa.Column('hours_worked', sa.Float(), nullable=False, server_default='0'),
        sa.Column('activity_id', sa.Integer, sa.ForeignKey('activity_codes.id'), nullable=True),
        sa.Column('cwp', sa.String(50), nullable=True),
        sa.Column('phase', sa.String(50), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_codes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_activity_codes_task_id', 'project_tasks', ['task_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###
