"""empty message

Revision ID: f5a7c5479d1a
Revises: 981df2019120
Create Date: 2025-01-07 18:02:10.168457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5a7c5479d1a'
down_revision = '981df2019120'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.alter_column('cost_per_unit',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.alter_column('cost_per_unit',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###
